# -*- coding: utf-8 -*-
"""Multiple Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PiFz0ADo_Oj8NBMhzguUgB8UgHmuThfl

# **Multiple Linear Regression**

## **Importing The Libraries**
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## **Importing the Dataset**"""

dataset = pd.read_csv('50_Startups.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

"""## **Encoding Categorical Data**"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

"""## **Train Test Split**"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

"""## **Training the Multiple Linear Regression Model**"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

"""## **Predicting Test Results**"""

y_pred = regressor.predict(x_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

"""### Q.How do I use my multiple linear regression model to make a single prediction, for example, the profit of a startup with R&D Spend = 160000, Administration Spend = 130000, Marketing Spend = 300000 and State = California?"""

print(regressor.predict([[1,0,0,160000,130000,300000]]))

"""### Q.How do I get the final regression equation y = b0 + b1 x1 + b2 x2 + ... with the final values of the coefficients?"""

print(regressor.coef_)
print(regressor.intercept_)