# -*- coding: utf-8 -*-
"""Simple Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hVr7usyq1yQN3Jg-hFzXG_bO4-SMtH1q

# **Simple Linear Regression**

## Importing the Libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing Dataset"""

dataset = pd.read_csv("Salary_Data.csv")
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values

"""## Train Test Split"""

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size = 0.2, random_state = 0)

"""## Training Simple Linear Regression Model on training Set"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

"""## Predicting The Test Set Results"""

y_pred = regressor.predict(X_test)

"""## Visulaising the Training Results"""

plt.scatter(X_train,Y_train,color = 'red')
plt.plot(X_train, regressor.predict(X_train), color = 'blue')
plt.title('Salary vs Experience (Trainig)')
plt.xlabel('Experience')
plt.ylabel('Salary')
plt.show()

"""## Visualising The Test Results"""

plt.scatter(X_test,Y_test,color = 'red')
plt.plot(X_train, regressor.predict(X_train), color = 'blue')
plt.title('Salary vs Experience (Test)')
plt.xlabel('Experience')
plt.ylabel('Salary')
plt.show()

"""### Q. Making a Single Prediction when years of Experience is 17."""

print(regressor.predict([[17]]))

"""### Q. How to get final Regression Equation Y = b0 + b1*X with final values of b0 and b1?"""

print(regressor.coef_)
print(regressor.intercept_)
