# -*- coding: utf-8 -*-
"""Decision Tree Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CHvdv17toXUUIEIvd_T5p_ETwrSvKFFH

# **Decision Tree Regression**

## **Importing The Libraries**
"""

import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

"""## **Importing the Dataset**"""

dataset = pd.read_csv('Position_Salaries.csv')
x = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

"""## **Training the Decision Tree Model on Entire Dataset**"""

from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(x,y)

"""## **Predict New Salary**"""

regressor.predict([[6.5]])

"""## **Visualising The Decision Tree Regression Model (in High Resolution)**"""

x_grid = np.arange(min(x),max(x),0.1)
x_grid = x_grid.reshape(len(x_grid),1)
plt.scatter(x,y,color = 'red')
plt.plot(x_grid,regressor.predict(x_grid),color = 'blue')
plt.title('Decision Tree Regression')
plt.xlabel('Position')
plt.ylabel('Salary')
plt.show()